[
  {
    municipio: {
      CODIGOINE: '08019000000',
      ID_REL: '1080193',
      COD_GEO: '08001',
      CODPROV: '08',
      NOMBRE_PROVINCIA: 'Barcelona',
      NOMBRE: 'Barcelona',
      POBLACION_MUNI: 1602386,
      SUPERFICIE: 9821.1086,
      PERIMETRO: 96341,
      CODIGOINE_CAPITAL: '08019000101',
      NOMBRE_CAPITAL: 'Barcelona',
      POBLACION_CAPITAL: '1602386',
      HOJA_MTN25: '0421-3',
      LONGITUD_ETRS89_REGCAN95: 2.17634927,
      LATITUD_ETRS89_REGCAN95: 41.38424664,
      ORIGEN_COORD: 'Mapa',
      ALTITUD: 13,
      ORIGEN_ALTITUD: 'MDT5',
      DISCREPANTE_INE: 0,
    },
    fecha: '2021-09-22',
    stateSky: { description: 'Cubierto', id: '16' },
    temperatura_actual: '24',
    temperaturas: { max: '27', min: '19' },
    humedad: '56',
    viento: '19',
    lluvia: '0',
    imagen: null,
    pronostico: {
      hoy: {
        '@attributes': { fecha: '2021-09-22', orto: '07:38', ocaso: '19:48' },
        estado_cielo: [
          '12',
          '16',
          '15',
          '16',
          '16',
          '16',
          '16',
          '16',
          '16',
          '46',
          '46',
          '44',
          '16n',
          '16n',
          '16n',
          '16n',
        ],
        precipitacion: [
          '0',
          '0',
          '0',
          '0',
          '0',
          '0',
          '0',
          '0',
          '0',
          '0.1',
          '0.1',
          '0.1',
          '0',
          '0',
          '0',
          '0',
        ],
        prob_precipitacion: ['30', '50', '20'],
        prob_tormenta: ['0', '5', '20'],
        nieve: [
          '0',
          '0',
          '0',
          '0',
          '0',
          '0',
          '0',
          '0',
          '0',
          '0',
          '0',
          '0',
          '0',
          '0',
          '0',
          '0',
        ],
        prob_nieve: ['0', '0', '0'],
        temperatura: [
          '21',
          '22',
          '23',
          '24',
          '24',
          '25',
          '25',
          '24',
          '24',
          '24',
          '23',
          '23',
          '23',
          '22',
          '22',
        ],
        sens_termica: [
          '21',
          '22',
          '23',
          '24',
          '24',
          '25',
          '25',
          '24',
          '24',
          '24',
          '23',
          '23',
          '23',
          '22',
          '22',
        ],
        humedad_relativa: [
          '59',
          '57',
          '54',
          '54',
          '52',
          '50',
          '51',
          '56',
          '57',
          '58',
          '61',
          '61',
          '61',
          '62',
          '63',
        ],
        viento: [
          { '@attributes': { periodo: '09' }, direccion: 'N', velocidad: '14' },
          {
            '@attributes': { periodo: '10' },
            direccion: 'NE',
            velocidad: '11',
          },
          {
            '@attributes': { periodo: '11' },
            direccion: 'NE',
            velocidad: '14',
          },
          {
            '@attributes': { periodo: '12' },
            direccion: 'NE',
            velocidad: '15',
          },
          {
            '@attributes': { periodo: '13' },
            direccion: 'NE',
            velocidad: '14',
          },
          { '@attributes': { periodo: '14' }, direccion: 'E', velocidad: '15' },
          { '@attributes': { periodo: '15' }, direccion: 'E', velocidad: '19' },
          { '@attributes': { periodo: '16' }, direccion: 'E', velocidad: '19' },
          {
            '@attributes': { periodo: '17' },
            direccion: 'NE',
            velocidad: '20',
          },
          {
            '@attributes': { periodo: '18' },
            direccion: 'NE',
            velocidad: '12',
          },
          {
            '@attributes': { periodo: '19' },
            direccion: 'NE',
            velocidad: '13',
          },
          {
            '@attributes': { periodo: '20' },
            direccion: 'NE',
            velocidad: '14',
          },
          {
            '@attributes': { periodo: '21' },
            direccion: 'NE',
            velocidad: '13',
          },
          {
            '@attributes': { periodo: '22' },
            direccion: 'NE',
            velocidad: '13',
          },
          { '@attributes': { periodo: '23' }, direccion: 'N', velocidad: '9' },
        ],
        racha_max: [
          '23',
          '26',
          '29',
          '28',
          '28',
          '34',
          '35',
          '35',
          '20',
          '25',
          '24',
          '21',
          '22',
          '15',
          '17',
        ],
      },
      manana: {
        '@attributes': { fecha: '2021-09-23', orto: '07:39', ocaso: '19:46' },
        estado_cielo: [
          '15n',
          '17n',
          '16n',
          '16n',
          '16n',
          '16n',
          '15n',
          '15n',
          '16',
          '12',
          '17',
          '12',
          '11',
          '17',
          '17',
          '16',
          '17',
          '17',
          '17',
          '17',
          '13n',
          '13n',
          '13n',
          '13n',
        ],
        precipitacion: [
          '0',
          '0',
          '0',
          '0',
          '0',
          '0',
          '0',
          '0',
          '0',
          '0',
          '0',
          '0',
          '0',
          '0',
          '0',
          '0',
          '0',
          '0',
          '0',
          '0',
          '0',
          '0',
          '0',
          '0',
        ],
        prob_precipitacion: ['30', '45', '25', '10'],
        prob_tormenta: ['30', '45', '25', '10'],
        nieve: [
          '0',
          '0',
          '0',
          '0',
          '0',
          '0',
          '0',
          '0',
          '0',
          '0',
          '0',
          '0',
          '0',
          '0',
          '0',
          '0',
          '0',
          '0',
          '0',
          '0',
          '0',
          '0',
          '0',
          '0',
        ],
        prob_nieve: ['0', '0', '0', '0'],
        temperatura: [
          '22',
          '22',
          '22',
          '22',
          '22',
          '22',
          '22',
          '22',
          '22',
          '22',
          '23',
          '24',
          '24',
          '25',
          '26',
          '26',
          '25',
          '25',
          '24',
          '23',
          '23',
          '22',
          '22',
          '21',
        ],
        sens_termica: [
          '22',
          '22',
          '22',
          '22',
          '22',
          '22',
          '22',
          '22',
          '22',
          '22',
          '23',
          '24',
          '24',
          '25',
          '26',
          '26',
          '25',
          '25',
          '24',
          '23',
          '23',
          '22',
          '22',
          '21',
        ],
        humedad_relativa: [
          '60',
          '60',
          '55',
          '55',
          '51',
          '49',
          '51',
          '54',
          '57',
          '55',
          '56',
          '48',
          '46',
          '46',
          '45',
          '51',
          '54',
          '58',
          '63',
          '61',
          '55',
          '60',
          '69',
          '67',
        ],
        viento: [
          {
            '@attributes': { periodo: '00' },
            direccion: 'NE',
            velocidad: '10',
          },
          {
            '@attributes': { periodo: '01' },
            direccion: 'NE',
            velocidad: '10',
          },
          {
            '@attributes': { periodo: '02' },
            direccion: 'NE',
            velocidad: '11',
          },
          {
            '@attributes': { periodo: '03' },
            direccion: 'NE',
            velocidad: '10',
          },
          { '@attributes': { periodo: '04' }, direccion: 'N', velocidad: '12' },
          {
            '@attributes': { periodo: '05' },
            direccion: 'NE',
            velocidad: '14',
          },
          { '@attributes': { periodo: '06' }, direccion: 'N', velocidad: '12' },
          {
            '@attributes': { periodo: '07' },
            direccion: 'NE',
            velocidad: '19',
          },
          {
            '@attributes': { periodo: '08' },
            direccion: 'NE',
            velocidad: '16',
          },
          { '@attributes': { periodo: '09' }, direccion: 'N', velocidad: '13' },
          {
            '@attributes': { periodo: '10' },
            direccion: 'NE',
            velocidad: '12',
          },
          {
            '@attributes': { periodo: '11' },
            direccion: 'NE',
            velocidad: '20',
          },
          {
            '@attributes': { periodo: '12' },
            direccion: 'NE',
            velocidad: '19',
          },
          { '@attributes': { periodo: '13' }, direccion: 'E', velocidad: '21' },
          { '@attributes': { periodo: '14' }, direccion: 'E', velocidad: '23' },
          { '@attributes': { periodo: '15' }, direccion: 'E', velocidad: '20' },
          { '@attributes': { periodo: '16' }, direccion: 'E', velocidad: '19' },
          { '@attributes': { periodo: '17' }, direccion: 'E', velocidad: '21' },
          { '@attributes': { periodo: '18' }, direccion: 'E', velocidad: '15' },
          { '@attributes': { periodo: '19' }, direccion: 'E', velocidad: '16' },
          { '@attributes': { periodo: '20' }, direccion: 'E', velocidad: '15' },
          { '@attributes': { periodo: '21' }, direccion: 'E', velocidad: '16' },
          {
            '@attributes': { periodo: '22' },
            direccion: 'NE',
            velocidad: '15',
          },
          {
            '@attributes': { periodo: '23' },
            direccion: 'NE',
            velocidad: '13',
          },
        ],
        racha_max: [
          '16',
          '22',
          '16',
          '20',
          '23',
          '20',
          '32',
          '27',
          '24',
          '23',
          '37',
          '36',
          '39',
          '42',
          '41',
          '39',
          '39',
          '31',
          '27',
          '25',
          '27',
          '25',
          '21',
          '24',
        ],
      },
    },
    proximos_dias: [
      {
        '@attributes': { fecha: '2021-09-23' },
        prob_precipitacion: ['65', '55', '25', '30', '45', '25', '10'],
        cota_nieve_prov: [
          { '@attributes': { periodo: '00-24' } },
          { '@attributes': { periodo: '00-12' } },
          { '@attributes': { periodo: '12-24' } },
          { '@attributes': { periodo: '00-06' } },
          { '@attributes': { periodo: '06-12' } },
          { '@attributes': { periodo: '12-18' } },
          { '@attributes': { periodo: '18-24' } },
        ],
        estado_cielo: ['43', '44', '13', '14n', '44', '13', '13'],
        viento: [
          {
            '@attributes': { periodo: '00-24' },
            direccion: 'E',
            velocidad: '25',
          },
          {
            '@attributes': { periodo: '00-12' },
            direccion: 'E',
            velocidad: '25',
          },
          {
            '@attributes': { periodo: '12-24' },
            direccion: 'E',
            velocidad: '25',
          },
          {
            '@attributes': { periodo: '00-06' },
            direccion: 'NE',
            velocidad: '15',
          },
          {
            '@attributes': { periodo: '06-12' },
            direccion: 'E',
            velocidad: '25',
          },
          {
            '@attributes': { periodo: '12-18' },
            direccion: 'E',
            velocidad: '15',
          },
          {
            '@attributes': { periodo: '18-24' },
            direccion: 'N',
            velocidad: '15',
          },
        ],
        racha_max: [
          '40',
          '40',
          '40',
          { '@attributes': { periodo: '00-06' } },
          '40',
          { '@attributes': { periodo: '12-18' } },
          { '@attributes': { periodo: '18-24' } },
        ],
        temperatura: {
          maxima: '26',
          minima: '20',
          dato: ['22', '26', '23', '20'],
        },
        sens_termica: {
          maxima: '26',
          minima: '20',
          dato: ['22', '26', '23', '20'],
        },
        humedad_relativa: {
          maxima: '70',
          minima: '45',
          dato: ['55', '45', '55', '65'],
        },
        uv_max: '5',
      },
      {
        '@attributes': { fecha: '2021-09-24' },
        prob_precipitacion: ['10', '0', '10'],
        cota_nieve_prov: [
          { '@attributes': { periodo: '00-24' } },
          { '@attributes': { periodo: '00-12' } },
          { '@attributes': { periodo: '12-24' } },
        ],
        estado_cielo: ['14', '14', '14'],
        viento: [
          {
            '@attributes': { periodo: '00-24' },
            direccion: 'E',
            velocidad: '20',
          },
          {
            '@attributes': { periodo: '00-12' },
            direccion: 'E',
            velocidad: '20',
          },
          {
            '@attributes': { periodo: '12-24' },
            direccion: 'E',
            velocidad: '20',
          },
        ],
        racha_max: ['40', '40', '40'],
        temperatura: { maxima: '27', minima: '20' },
        sens_termica: { maxima: '27', minima: '20' },
        humedad_relativa: { maxima: '70', minima: '45' },
        uv_max: '6',
      },
      {
        '@attributes': { fecha: '2021-09-25' },
        prob_precipitacion: ['25', '10', '15'],
        cota_nieve_prov: [
          { '@attributes': { periodo: '00-24' } },
          { '@attributes': { periodo: '00-12' } },
          { '@attributes': { periodo: '12-24' } },
        ],
        estado_cielo: ['13', '13', '13'],
        viento: [
          {
            '@attributes': { periodo: '00-24' },
            direccion: 'S',
            velocidad: '15',
          },
          {
            '@attributes': { periodo: '00-12' },
            direccion: 'S',
            velocidad: '15',
          },
          {
            '@attributes': { periodo: '12-24' },
            direccion: 'S',
            velocidad: '15',
          },
        ],
        racha_max: [
          { '@attributes': { periodo: '00-24' } },
          { '@attributes': { periodo: '00-12' } },
          { '@attributes': { periodo: '12-24' } },
        ],
        temperatura: { maxima: '29', minima: '22' },
        sens_termica: { maxima: '29', minima: '22' },
        humedad_relativa: { maxima: '85', minima: '65' },
        uv_max: '5',
      },
      {
        '@attributes': { fecha: '2021-09-26' },
        prob_precipitacion: '10',
        cota_nieve_prov: {},
        estado_cielo: '13',
        viento: { direccion: 'O', velocidad: '10' },
        racha_max: {},
        temperatura: { maxima: '30', minima: '20' },
        sens_termica: { maxima: '30', minima: '20' },
        humedad_relativa: { maxima: '85', minima: '40' },
        uv_max: '5',
      },
      {
        '@attributes': { fecha: '2021-09-27' },
        prob_precipitacion: '0',
        cota_nieve_prov: {},
        estado_cielo: '12',
        viento: { direccion: 'SE', velocidad: '10' },
        racha_max: {},
        temperatura: { maxima: '28', minima: '18' },
        sens_termica: { maxima: '28', minima: '18' },
        humedad_relativa: { maxima: '90', minima: '50' },
      },
      {
        '@attributes': { fecha: '2021-09-28' },
        prob_precipitacion: '35',
        cota_nieve_prov: {},
        estado_cielo: '13',
        viento: { direccion: 'S', velocidad: '10' },
        racha_max: {},
        temperatura: { maxima: '27', minima: '19' },
        sens_termica: { maxima: '27', minima: '19' },
        humedad_relativa: { maxima: '85', minima: '60' },
      },
    ],
    breadcrumb: [
      {
        name: 'Provincias',
        url: '/provincias',
        title: 'El tiempo | Lista de provincias',
      },
      {
        name: 'Barcelona',
        url: '/provincias/08',
        title: 'El tiempo en la provincia de Barcelona',
      },
      {
        name: 'Municipios',
        url: '/provincias/08/municipios',
        title: 'El tiempo | Lista de municipios de Barcelona',
      },
      {
        name: 'Barcelona',
        url: '/provincias/08/municipios/08001',
        title: 'El tiempo en Barcelona',
      },
    ],
    keywords:
      'Barcelona, Provincia de Barcelona, previsi\u00f3n meteorol\u00f3gica, previsi\u00f3n del tiempo, Espa\u00f1a, viento, humedad, precipitaciones, lluvia, estado del cielo',
  },
];
